---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-15.04
  - name: debian-8.2
  - name: centos-7.1

suites:
  - name: default
    run_list:
      recipe[bitmonk_java]
    attributes:
      tomcat:
        base_version: 8
